name: Test workflow for debugging

# Controls when the action will run.
on:
  #schedule:
    # Run at midnight UTC (4 pm PDT) Mon thru Fri
    #- cron: "30 22 * * 1-5"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-env:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
        with:
          lfs: true

      # Force checkout to explicitly using lfs to ensure the pointer files are replaced with the actual file content
      - name: Checkout LFS objects
        run: git lfs checkout

        # set the current date in environment to be used for appending to filenames in subsequent steps
      - name: current-date
        run: echo "DATE='2025-09-10'" >> $GITHUB_ENV

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Run test script
      - name: execute-test
        run: |
          #echo "Github_workspace: $GITHUB_WORKSPACE"
          #ls -la $GITHUB_WORKSPACE/*
          pip list
          echo "Running test program directly"
          python $GITHUB_WORKSPACE/src/artha_data/batch/test-workflow.py
          echo "Running test script from $GITHUB_WORKSPACE"
          $GITHUB_WORKSPACE/scripts/test-script.sh ${{ env.DATE }}
          which python
